/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 static/models/information/static/base.glb --transform false 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/base.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor008.geometry} material={nodes.floor008.material} scale={[25, 25, 24.981]} />
      <mesh geometry={nodes.shadeBrown049.geometry} material={nodes.shadeBrown049.material} position={[7.011, 8.461, 0.569]} rotation={[0, 0, Math.PI]} scale={1.178} />
      <mesh geometry={nodes.shadeBrown056.geometry} material={nodes.shadeBrown056.material} position={[-8.841, 1.029, 0.569]} rotation={[0, 0, -Math.PI / 2]} scale={1.178} />
      <mesh geometry={nodes.shadeBrown057.geometry} material={nodes.shadeBrown057.material} position={[-6.336, -10.023, 0.569]} scale={1.178} />
      <mesh geometry={nodes.shadeGreen002.geometry} material={nodes.shadeGreen002.material} position={[7.011, 8.461, 1.271]} rotation={[0, 0, Math.PI]} scale={1.178} />
      <mesh geometry={nodes.shadeGreen011.geometry} material={nodes.shadeGreen011.material} position={[-8.841, 1.029, 1.271]} rotation={[0, 0, -Math.PI / 2]} scale={1.178} />
      <mesh geometry={nodes.shadeGreen014.geometry} material={nodes.shadeGreen014.material} position={[-6.336, -10.023, 1.271]} scale={1.178} />
      <mesh geometry={nodes.shadeWhite_002004.geometry} material={nodes.shadeWhite_002004.material} position={[4.311, 6.508, 0.017]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.shadeWhite_003004.geometry} material={nodes.shadeWhite_003004.material} position={[-8.163, 0.201, 0.025]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.shadeWhite_015026.geometry} material={nodes.shadeWhite_015026.material} position={[5.23, 7.194, 0]} scale={0.156} />
      <mesh geometry={nodes.shadeWhite_015027.geometry} material={nodes.shadeWhite_015027.material} position={[-8.376, -0.914, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.156} />
      <mesh geometry={nodes.shadeWhite_015028.geometry} material={nodes.shadeWhite_015028.material} position={[10.881, -0.059, 0]} scale={0.156} />
      <mesh geometry={nodes.shadeWhite_015031.geometry} material={nodes.shadeWhite_015031.material} position={[11.134, -0.259, 0]} scale={0.156} />
      <mesh geometry={nodes.shadeRed001.geometry} material={nodes.shadeRed001.material} position={[-4.356, 4.152, 1.24]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.291} />
      <mesh geometry={nodes.shadeGray007.geometry} material={nodes.shadeGray007.material} position={[-6.171, 6.371, 0.003]} rotation={[0, 0, Math.PI]} scale={1.092} />
      <mesh geometry={nodes.shadeWhite111.geometry} material={nodes.shadeWhite111.material} position={[-4.231, 5.061, 1.704]} rotation={[0, 0, Math.PI]} scale={[1.997, 1.997, 2.336]} />
      <mesh geometry={nodes.shadeWhite.geometry} material={nodes.shadeWhite.material} position={[-4.231, 5.061, 3.487]} rotation={[0, 0, Math.PI]} scale={1.997} />
      <mesh geometry={nodes.shadeWhite112.geometry} material={nodes.shadeWhite112.material} position={[-3.236, 5.061, 2.855]} rotation={[0, 0, Math.PI]} scale={1.997} />
      <mesh geometry={nodes.shadeRed005.geometry} material={nodes.shadeRed005.material} position={[-3.236, 5.061, 2.855]} rotation={[0, 0, Math.PI]} scale={1.997} />
      <mesh geometry={nodes.shadeBlue.geometry} material={nodes.shadeBlue.material} position={[-3.236, 5.061, 2.855]} rotation={[0, 0, Math.PI]} scale={1.997} />
      <mesh geometry={nodes.shadeOrange024.geometry} material={nodes.shadeOrange024.material} position={[4.272, 0.667, 0.012]} scale={1.164} />
      <mesh geometry={nodes.shadeWhite114.geometry} material={nodes.shadeWhite114.material} position={[4.281, 0.667, 0.252]} scale={1.164} />
      <mesh geometry={nodes.shadeWhite_033.geometry} material={nodes.shadeWhite_033.material} position={[1.88, 0.667, 0.252]} scale={1.164} />
      <mesh geometry={nodes.shadeOrange005.geometry} material={nodes.shadeOrange005.material} position={[1.88, 0.667, 0.012]} scale={1.164} />
      <mesh geometry={nodes.shadeOrange003.geometry} material={nodes.shadeOrange003.material} position={[6.68, 0.667, 0.012]} rotation={[Math.PI / 2, 0.262, 0]} scale={139.08} />
      <mesh geometry={nodes.shadeWhite115.geometry} material={nodes.shadeWhite115.material} position={[6.678, 0.667, 0.252]} scale={1.164} />
      <mesh geometry={nodes.shadeOrange006.geometry} material={nodes.shadeOrange006.material} position={[9.064, 0.753, -0.087]} rotation={[0, 0, Math.PI / 2]} scale={1.334} />
      <mesh geometry={nodes.shadeWhite_036.geometry} material={nodes.shadeWhite_036.material} position={[9.398, 0.451, 1.47]} scale={1.334} />
      <mesh geometry={nodes.shadeWhite_037.geometry} material={nodes.shadeWhite_037.material} position={[8.965, 0.761, 1.28]} scale={1.334} />
      <mesh geometry={nodes.shadeWhite_038.geometry} material={nodes.shadeWhite_038.material} position={[9.169, 0.386, 1.286]} rotation={[-0.009, 0.088, -0.246]} scale={1.334} />
      <mesh geometry={nodes.shadeWhite_039.geometry} material={nodes.shadeWhite_039.material} position={[9.158, -0.093, 1.101]} rotation={[0.487, 0, 0.481]} scale={1.334} />
      <mesh geometry={nodes.shadeOrange022.geometry} material={nodes.shadeOrange022.material} position={[9.064, 0.921, 0.844]} scale={1.334} />
      <mesh geometry={nodes.shadeWhite116.geometry} material={nodes.shadeWhite116.material} position={[9.078, 0.667, 0.252]} scale={1.164} />
    </group>
  )
}

useGLTF.preload('/base.glb')
