spring.application.name=ServicePret
server.port=8086

spring.mvc.log-request-details=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.datasource.url=jdbc:mysql://localhost:3306/gestionPret?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.config.enabled=false


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=-1

crypto.master.secret=${CRYPTO_MASTER_SECRET}
#server.servlet.context-path=/pret
stripe.secret.key=${STRIPE_SECRET_KEY}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
groq.api.key=${GROQ_API_KEY:}
fraud.analysis.timeout=120

contrat.storage.path=uploads/contrats/