spring.application.name=gateway
#spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false

server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=gateway
info.app.version=0.0.1-SNAPSHOT

#spring.cloud.gateway.server.webmvc.routes[0].id=livraison-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=lb://LIVRAISON-SERVICE
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/livraison/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1
#Gestion user
spring.cloud.gateway.server.webmvc.routes[0].id=gestion-user
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://GESTION-USER
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

#Gestion Formation
#spring.cloud.gateway.server.webmvc.routes[1].id=livraison-service
#spring.cloud.gateway.server.webmvc.routes[1].uri=lb://LIVRAISON-SERVICE
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/livraison/**
#spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# Gestion Forum
spring.cloud.gateway.server.webmvc.routes[1].id=gestion-forum
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://GESTION-FORUM
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/forums,/forums/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# Gestion Livraison
spring.cloud.gateway.server.webmvc.routes[2].id=livraison-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://LIVRAISON-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/livraison/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

# Gestion Explorer 3D
spring.cloud.gateway.server.webmvc.routes[3].id=explorer-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://EXPLORER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/explorer/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

# Gestion Formation
spring.cloud.gateway.server.webmvc.routes[4].id=gestion-formation
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://GESTION-FORMATION
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/formation/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1

# Gestion Evenement
spring.cloud.gateway.server.webmvc.routes[5].id=gestion-evenement
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://GESTIONEVENEMENT
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/evenement/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

# Gestion Vente & Location
spring.cloud.gateway.server.webmvc.routes[6].id=gestion-vente
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://GESTION-VENTE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/Vente/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=StripPrefix=1

# Farmer Support (terrains, parcelles, cultures, rappels)
spring.cloud.gateway.server.webmvc.routes[7].id=farmer-support
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://FARMER-SUPPORT
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/support/**
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=StripPrefix=1

# Gestion Loans
spring.cloud.gateway.server.webmvc.routes[8].id=service-pret
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://SERVICEPRET
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/pret/**
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=StripPrefix=1

# Gestion Inventaire
spring.cloud.gateway.server.webmvc.routes[9].id=gestion-inventaire
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://GESTION-INVENTAIRE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/inventaires/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=StripPrefix=1

# Assistance Service
spring.cloud.gateway.server.webmvc.routes[10].id=assistance-service
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://ASSISTANCE-SERVICE
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/assistance/**
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=StripPrefix=1

# Payment Service
spring.cloud.gateway.server.webmvc.routes[11].id=payment-service
spring.cloud.gateway.server.webmvc.routes[11].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/paiement/**
spring.cloud.gateway.server.webmvc.routes[11].filters[0]=StripPrefix=1

spring.cloud.config.import-check.enabled=false
